#!/bin/bash
binpath=/usr/local/bin/

cp ./etc/om.config /etc/om.config
cp ./sh/om_config $binpath
cp ./sh/dh/om_delete_property $binpath
cp ./sh/dh/om_copy_property $binpath
cp ./sh/dh/om_get_propnames $binpath
cp ./sh/dh/om_copy_all_props $binpath
cp ./sh/dh/om_get_by_pid $binpath
cp ./sh/dh/om_get_prop $binpath
cp ./sh/dh/om_set_prop $binpath
