#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Use: om_element_tree elementid [include_children=1] [max_recursion_level=-1(all)] [exclude_custom1=-1]" 1>&2
  exit
fi
. om_config
elid=$1
include_children=1
if [ $# -gt 1 ]; then
  include_children=$2
fi
mrl=-1
if [ $# -gt 2 ]; then
  mrl=$3
fi
exclude_custom1="-1"
if [ $# -gt 3 ]; then
  exclude_custom1=$4
fi
echo "Called:  om_element_tree $elid $include_children" 1>&2

#sql="\\set elid $elid \n
#\\set include_children $include_children \n
sql="WITH RECURSIVE element_tree AS (
      SELECT p.*, 0 AS level
      FROM map_model_linkages as p
      WHERE p.dest_id = $elid 
        AND linktype = 1
      UNION
      SELECT c.*, p.level + 1 as level
      FROM map_model_linkages as c 
      left outer join scen_model_element as e
      on (
        e.elementid = c.src_id
      )
      inner join element_tree as p
      on (c.dest_id = p.src_id and c.linktype = 1 and $include_children = 1)
      WHERE ( (e.custom1 <> '$exclude_custom1') OR ('$exclude_custom1' = '-1') )
    )
SELECT src_id from element_tree 
where (level <= $mrl) OR ($mrl = -1);"

echo $sql 1>&2
#set -f
echo -e $sql | psql -t -h $DB_HOST model 
