#!/bin/sh
# This adds common data matrixes from a template that do not get created 
# by default with the model type plugin
template=4988636
if [ $# -lt 1 ]; then
  echo 1>&2 "Usage: add_common_waterSystemElement.sh pid  [template=default($template)] [overwrite=0] [debug=0]"
  exit 2
fi
pid=$1
if [ $# -gt 1 ]; then
  if [ "$2" != "default" ]; then
    template=$2
  fi
fi  
overwrite=0
if [ $# -gt 2 ]; then
  overwrite=$3
fi 
debug=0
if [ $# -gt 3 ]; then
  debug=$4
fi 

om_copy_property dh_properties $template dh_properties $pid custom1 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid permit_status 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid ps_enabled 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid ps_local_mgd 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid ps_nextdown_mgd 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid ps_other_mgd 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid fac_demand_mgy 1 $overwrite $debug 
om_copy_property dh_properties $template dh_properties $pid wd_mgd 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid discharge_mgd 1 $overwrite $debug 
om_copy_property dh_properties $template dh_properties $pid process_discharge_frac 1 $overwrite $debug 
om_copy_property dh_properties $template dh_properties $pid discharge_local_mgd 1 $overwrite $debug 
om_copy_property dh_properties $template dh_properties $pid discharge_other_mgd 1 $overwrite $debug 
om_copy_property dh_properties $template dh_properties $pid gw_sw_factor 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid gw_demand_mgd 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid discharge_from_gw_mgd 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid historic_monthly_pct 1 0 $debug
om_copy_property dh_properties $template dh_properties $pid "Send to Parent" 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid "Listen on Parent" 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid gw_frac 1 0 $debug
