#!/bin/sh
# This adds common data matrixes from a template that do not get created 
# by default with the model type plugin
pid=$1
template=7423559

if [ $# -lt 1 ]; then
  echo 1>&2 "Usage: add_local_tributaries_broadcasts pid [template=$template]"
  exit 2
fi 

if [ $# -gt 1 ]; then
  template=$2
fi 
overwrite=0
if [ $# -gt 2 ]; then
  overwrite=$3
fi 
debug=0
if [ $# -gt 3 ]; then
  debug=$4
fi 


om_copy_property dh_properties $template dh_properties $pid "Broadcast on Parent" 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid "Broadcast on Child" 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid "Listen on Parent" 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid "Listen on Child" 1 $overwrite $debug


