#!/bin/bash

if [ $# -lt 5 ]; then
  echo 1>&2 "Usage: om_copy_all_props src_entity_type src_featureid dest_entity_type dest_featureid [include_children=1] [overwrite=0] [debug=0]"
  exit 2
fi 

src_entity_type=$1
src_featureid=$2
dest_entity_type=$3
dest_featureid=$4
IFS="|" read propname dest_name <<< "$5"
if [ "$dest_name" == "" ]; then
  dest_name=$propname
fi 
include_children=1
if [ $# -gt 5 ]; then
  include_children=$6
fi 
overwrite=0
if [ $# -gt 6 ]; then
  overwrite=$7
fi 
debug=0
if [ $# -gt 7 ]; then
  debug=$8
fi 

lns=`om_get_propnames $src_entity_type $src_featureid`
IFS=$(echo -en "\n\b")
for i in $lns; do 
  echo "om_copy_property $src_entity_type $src_featureid $dest_entity_type $dest_featureid $i $include_children $overwrite $debug"
done
