#!/bin/bash
. om_config

if [ $# -lt 3 ]; then
  echo 1>&2 "Usage: om_delete_property entity_type featureid propname "
  echo 1>&2 "Usage: om_delete_property dh_feature 146 wd_current_mgy"
  exit 2
fi 

entity_type=$1
featureid=$2
prop_name=$3

delete_sql="

BEGIN; \n

create temp table tmp_exist_prop as select * from dh_properties_fielded limit 0; \n

WITH RECURSIVE exist_prop AS ( \n
      SELECT base.*
      FROM dh_properties_fielded as base
      WHERE base.featureid = $featureid
        AND propname = '$prop_name' 
        AND base.entity_type = '$entity_type'
      UNION
      SELECT c.*
      FROM dh_properties_fielded as c 
      inner join exist_prop as p
      on (c.featureid = p.pid and c.entity_type = 'dh_properties')
    ) \n
INSERT INTO tmp_exist_prop SELECT * from exist_prop; \n

DELETE FROM dh_properties where pid in (select pid from tmp_exist_prop); \n

DELETE FROM dh_properties_revision where pid in (select pid from tmp_exist_prop); \n

DELETE FROM field_data_field_dh_matrix WHERE entity_type = 'dh_properties' AND entity_id in (select pid from tmp_exist_prop); \n

DELETE FROM field_data_proptext WHERE entity_type = 'dh_properties' AND entity_id in (select pid from tmp_exist_prop); \n

DELETE FROM field_data_field_projection_table WHERE entity_type = 'dh_properties' AND entity_id in (select pid from tmp_exist_prop); \n

COMMIT; \n 
"
echo "echo $delete_sql | psql -h $DB_HOST $DB_NAME"
set -f
echo -e $delete_sql | psql -h $DB_HOST $DB_NAME
