#!/bin/bash
. om_config

if [ $# -lt 2 ]; then
  echo 1>&2 "Usage: om_get_propnames src_entity_type src_featureid [debug=0]"
  exit 2
fi 

src_entity_type=$1
src_featureid=$2

# select STRING_AGG(E'\\'' ||o.propname || E'\\'', ' ')

sql="
\\o \n


  select o.propname

  from dh_properties as e
  WHER e.pid = $src_featureid
    and e.entity_type = '$src_entity_type'
"


set -f
# can't echo this to stdout or it clobbers script pipes
#echo -e "$sql | psql --csv -A --field-separator=',' -t -h $DB_HOST $DB_NAME"
echo -e $sql | psql --csv -A --field-separator=" " -t -h $DB_HOST $DB_NAME
