#!/bin/bash
. om_config

if [ $# -lt 2 ]; then
  echo 1>&2 "Usage: om_get_prop src_entity_type src_featureid propname target[propvalue,propcode,pid] [debug=0]"
  exit 2
fi 
pid=$1
src_entity_type=$1
src_featureid=$2
propname=$3
target="propvalue"
if [ $# -gt 3 ]; then 
  target=$4
fi
debug=0
if [ $# -gt 4 ]; then 
  debug=$5
fi


sql="
\\o \n

  select e.${target}
  from dh_properties_fielded as e
  WHERE e.featureid = $src_featureid
    and e.entity_type = '$src_entity_type'
    and e.propname = '$propname'
"
i
set -f
echo -e $sql | psql --csv -A --field-separator=" " -t -h $DB_HOST $DB_NAME
