#!/bin/sh

# Water Supply Model Element Template 
template=4988636
if [ $# -lt 1 ]; then
  echo 1>&2 "Usage: set_exempt_props vahydro_model_pid [template=default($template)] [overwrite=0] [debug=0]"
  exit 2
fi
pid=$1
if [ $# -gt 1 ]; then
  if [ "$2" != "default" ]; then
    template=$2
  fi
fi  
overwrite=0
if [ $# -gt 2 ]; then
  overwrite=$3
fi 
debug=0
if [ $# -gt 3 ]; then
  debug=$4
fi 


# make sure it is using the new discharge_mgd variable 
om_copy_property dh_properties $template dh_properties $pid vwp_exempt_2025_mgd 1 $overwrite $debug
om_copy_property dh_properties $template dh_properties $pid flowby_exempt 1 $overwrite $debug
# needs up to date main flowby var to allow selection of flowby_exempt based on run_mode
om_copy_property dh_properties $template dh_properties $pid flowby 1 $overwrite $debug

