#!/bin/sh
# Water Supply Model Element Template 
template=6717035

if [ $# -lt 1 ]; then
  echo 1>&2 "Usage: set_impoundment_release_rules.sh vahydro_model_pid [template=default($template)] [overwrite=0] [debug=0]"
  exit 2
fi
pid=$1
if [ $# -gt 1 ]; then
  if [ "$2" != "default" ]; then
    template=$2
  fi
fi  
overwrite=0
if [ $# -gt 2 ]; then
  overwrite=$3
fi 
debug=0
if [ $# -gt 3 ]; then
  debug=$4
fi 


# Set destination model to not write
#drush scr modules/om/src/om_setprop.php cmd dh_properties $pid om_element_connection om_element_connection $elementid 0

# make sure it is using the new discharge_mgd variable 
for i in release release_current release_historic release_proposed refill_transfer_available_mgd refill_transfer_max_mgd; do
  echo "om_copy_property dh_properties $template dh_properties $pid $i 1 $overwrite"
  om_copy_property dh_properties $template dh_properties $pid $i 1 $overwrite $debug
done

# Restore destination write setting and save
#drush scr modules/om/src/om_setprop.php cmd dh_properties $pid om_element_connection om_element_connection $elementid 1

echo "Finished. Note, if you wish to control a remote impoundment, you must also run set_impoundment_release_sender.sh"
