#!/bin/sh

# Water Supply Model Element Template 
template=6403272
if [ $# -lt 1 ]; then
  echo 1>&2 "Usage: set_reservoir_system_props.sh vahydro_model_pid [template=default($template)] [overwrite=0] [debug=0]"
  exit 2
fi
pid=$1
if [ $# -gt 1 ]; then
  if [ "$2" != "default" ]; then
    template=$2
  fi
fi  
overwrite=0
if [ $# -gt 2 ]; then
  overwrite=$3
fi 
debug=0
if [ $# -gt 3 ]; then
  debug=$4
fi 


# make sure it is using the new discharge_mgd variable 
om_copy_property dh_properties $template dh_properties $pid available_mgd 1 $overwrite $debug

