#!/bin/sh
# Water Supply Model Element Template 
template=6717035

if [ $# -lt 1 ]; then
  echo 1>&2 "Usage: set_impoundment_release_sender vahydro_model_pid [template=$template] [overwrite=0]"
  exit 2
fi
pid=$1
if [ $# -gt 1 ]; then
  template=$2
fi 
if [ $# -gt 2 ]; then
  overwrite=$3
fi 


# make sure it is using the new discharge_mgd variable 
om_copy_property dh_properties $template dh_properties $pid "Reservoir Operations" 1 $overwrite
# make sure it has the latest greatest broadcast info which include Qnextdown 1 $overwrite
om_copy_property dh_properties $template dh_properties $pid "Listen on Parent" 1 $overwrite
om_copy_property dh_properties $template dh_properties $pid control_impoundment 1 $overwrite
om_copy_property dh_properties $template dh_properties $pid impoundment_release_cfs 1 $overwrite

